name: Build and Push Docker Image to Docker Hub

on: [push, workflow_dispatch]
jobs:
  push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: actions/checkout@v4

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: johnbin89/divephotomapui:latest
          build-args: |
            NEXT_PUBLIC_DJ_URL=${{ secrets.NEXT_PUBLIC_DJ_URL }}
            
      - name: triggerjenkinsjob
        uses: mickeygoussetorg/trigger-jenkins-job@v1
        with:
          jenkins-server:  "${{ secrets.JENKINS_HOST }}" # URL of the jenkins server. ex: http://myjenkins.acme.com:8080
          jenkins-job: "DivePhotoMapUI" # The name of the jenkins job to run
          jenkins-username: ${{ secrets.JENKINS_USER }} # user name for accessing jenkins
          jenkins-pat: ${{ secrets.JENKINS_TOKEN }} # personal Access token for accessing Jenkins
          poll-time: 10 # how often (seconds) to poll the jenkins server for results
          timeout-value: 600 # How long (seconds) to poll before timing out the action
          verbose: true # true/false - turns on extra logging
